services:
  - type: web
    name: warnsveld-platform
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_PATH
        value: database.db

